### ISSUE TITLE
Show number of errored samples

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#101]
**Feature Category**

- [x] Correctness
- [x] User Interface / User Experience
- [ ] Performance
- [ ] Other (please explain)

**Describe the problem**

When yara rule matching fails (for example, file does not exist), we just silently ignore the match and don't inform the user about the problem.

**Describe the solution you'd like**

Show a number of errors in the UI and on the progress bar (in red)

**Describe alternatives you've considered**

Change query status to `errored` after every error? Probably too harsh.

**Comment by KWMORALE** [comment]
![image](https://user-images.githubusercontent.com/63305564/80708556-2d96e480-8aec-11ea-9743-b5e5b35035ac.png)
