### ISSUE TITLE
Clicking on the logo should take you to a clean page

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#158]
**Environment information**
* Mquery version (from the /status page):
* Ursadb version (from the /status page):
* Installation method:
  - [x] Generic docker-compose
  - [x] Dev docker-compose
  - [ ] Native (from source)
  - [ ] Other (please explain)

**Reproduction Steps + Actual behaviour**
When you are is a specific task\query and clicking on the Cert.pl logo on the top of the page, t
it does nothing except changing the url.

**Expected behaviour**

I expect the page to go for a clean query page so I can write a new query

**Screenshots**

The following gif shows that clicking the logo doesnt work as expected. and when opening in new tab it does
![Peek 2020-05-11 18-53](https://user-images.githubusercontent.com/20182642/81582505-cf55e580-93b8-11ea-8e60-d161f54a6dc1.gif)

**Comment by JaroPowerH** [comment]
I would like to work on this issue.
