### ISSUE TITLE
Download a list of matched filenames

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#173]
**Feature Category**

- [ ] Correctness
- [x] User Interface / User Experience
- [ ] Performance
- [ ] Other (please explain)

**Describe the problem**

There is no way to download the list of filenames for all matched samples.

**Describe the solution you'd like**

Add another button next to the others in the `matches` table

![ss](https://user-images.githubusercontent.com/7026881/82096105-a444fc00-9700-11ea-9c18-40190145d1fd.png)

**Describe alternatives you've considered**

Download filenames as .txt, after #34 is done

**Comment by ITAYC0HEN** [comment]
might be too noisy on the ui. we can have a download button that opens a small combo box that shows several options
