### ISSUE TITLE
Unable to use Regex within Yara Rules

### ISSUE THREAD

**Issue by darksheer** [CERT-Polska/mquery#18]
Here's an example of the failed query using Yara regex. 

https://mquery.tailcall.net/query/Q306ZVWGLIRA

**Comment by icedevml** [comment]
Hello, unfortunately mquery doesn't support the whole YARA, only some selected subset. Our optimizer is not powerful enough to handle regexes. You would have to rewrite the rule to something simpler.

/cc @msm-code

**Comment by msm-code** [comment]
Hi,

it should work better now. The optimiser will still ignore regexes, but it will at least try to execute the rule.
