### ISSUE TITLE
Show number of total indexed files in the Status page

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#19]
**Description**
The `/status` page is used to provide information about the underlying infrastructure, including versions, topology, and current connections.
If a user wants to know how many files are indexed, there's no clear way to do so (unless ursadb-cli provides it somehow, and still - it is no accessible).

My suggestion is to display the number of indexed files in the dataset(s). It will also be nice-to-have to show the number of files that aren't indexed because `ls /mnt/samples | wc -l != num_of_indexex_files`.

A bonus feature would be to show a total size of the dataset.

**Comment by icedevml** [comment]
@ITAYC0HEN Hello. Thanks for your input, we will look at all of these tickets soon.

If you have some spare time, then pull requests are also welcome :)

**Comment by ITAYC0HEN** [comment]
@icedevml thank you for the great work! most of the issues/feature-requests are already informed to @msm-code on our chats, so I hope I didn't caught you in too big of a shock.

Moreover, the most important and interesting features were not submitted yet, and I'll fill them tomorrow :)

**Comment by ITAYC0HEN** [comment]
And of course, pull requests will be submitted when I get a better grip in the codebase.

**Comment by msm-code** [comment]
Thanks for your help again!

> It will also be nice-to-have to show the number of files that aren't indexed because ls /mnt/samples | wc -l != num_of_indexex_files.

That's harder to implement than it looks like. (To avoid technical details, ursadb only knows about indexed samples and also there's nothing stopping you from indexing files in various directories).

OTOH this sounds like a valid use case for most common deploymen. If you don't mind, I've created a separate issue for it (#42)
