### ISSUE TITLE
Should we apply word-wrapping in Monaco?

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#195]
**Feature Category**

- [x] User Interface / User Experience

**Describe the problem**

Currently, there is no word wrap in the Monaco editor and the users need to scroll horizontally

![image](https://user-images.githubusercontent.com/20182642/82443733-a44f4e00-9aaa-11ea-9d57-9fa62c43ab9a.png)

**Describe alternatives you've considered**

I see three options here:
 - Keep it as-is, it's fine
 - Enable word-wrap
 - Add a button to toggle word wrap

What do you think?

**Comment by msm-code** [comment]
Related problem - there is a way to hide query editor, but no way to hide the query results. So it's either `40% editor 60% results` or `100% result`.

Maybe we should:
 - increase the default editor width to at least 50% (not sure about it yet)
 - Enforced minimal editor width, and when the window is too narrow collapse the matches view completely

This won't solve the problem, but may make it less important in practice. 

I had this problem when I tried to record a screencast: I wanted to make a browser window smaller, but query editor quickly became too narrow to be useful.
