### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by echin20** [CERT-Polska/mquery#2]
I am getting the following error when I  run "docker-compose up --scale daemon=3"

Successfully tagged mquery_daemon:latest
Building web
ERROR: No build stage in current context

**Comment by icedevml** [comment]
Could you provide more information? What system are you using, which version of Docker and docker-compose?

**Comment by echin20** [comment]
Here are the version I am running. 

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.2, build a133471

CentOS Linux release 7.5.1804 (Core)

**Comment by icedevml** [comment]
What commands are you executing?

My flow is:
```
git clone --recursive https://github.com/CERT-Polska/mquery.git
cd mquery
docker-compose up --build
```

and it works well.

**Comment by echin20** [comment]
I tired following the direction on the readme.

git clone --recurse-submodules https://github.com/CERT-Polska/mquery.git
cd mquery
docker-compose up --scale daemon=3

I just tried the command above, but still getting the same error. Here is the chain leading up to the error. 
docker-compose up --build

Step 1/6 : FROM python:2.7
 ---> e06629951c72
Step 2/6 : COPY . /app
 ---> Using cache
 ---> 5d52cde112a9
Step 3/6 : RUN pip install -r /app/requirements.txt
 ---> Using cache
 ---> 998d5ce8eca4
Step 4/6 : RUN python /app/docker-mkconf.py
 ---> Using cache
 ---> baa65f142a2e
Step 5/6 : RUN chmod +x /app/daemon.py
 ---> Using cache
 ---> b2695a68b21c
Step 6/6 : ENTRYPOINT [ "/app/daemon.py" ]
 ---> Using cache
 ---> f96231afb9ba
Successfully built f96231afb9ba
Successfully tagged mquery_daemon:latest
Building web
ERROR: No build stage in current context

**Comment by echin20** [comment]
I was able to figure out my issue. I had some erroneous proxy settings in the Dockerfile.
