### ISSUE TITLE
Show number of detected samples per each job in "Recent Jobs"

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#20]
When visiting the `/recent` page, there is no way to understand how many samples detected in each job. This is a useful feature that I think would be easy to implement. 

An example can be found in VT's retrohunt page:
![image](https://user-images.githubusercontent.com/20182642/78378170-47bad100-75d9-11ea-873a-fcccffb306b3.png)

**Comment by msm-code** [comment]
Fixed with #129
