### ISSUE TITLE
Filter previous jobs by author

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#22]
**Description**
Currently, mqeury parses the rule's author from the metadata part in the rule.

When the number of jobs will start to rise, it would be harder to return to find a previous job. It's even more important if a big organization is using mquery with > 10 daily users.
Thus, it would be nice to have an option to filter the jobs by their author.

![image](https://user-images.githubusercontent.com/20182642/78379191-aaf93300-75da-11ea-8f18-409860981414.png)

---

*In general, I believe that implementing user management would be a good decision. Maybe something that is based on mwdb user permission model. This will help to make mquery suitable for big organizations. For example, some queries are too sensitive to share even with other people in the same organization. In addition, the author signed on a Yara rule isn't necessarily the person who executes the yara. Say, if someone is executing a rule from the internet written by a stranger.  Later, it will be hard for them to find this job since they don't remember the name of the stranger.

I'll open a new issue for this ^*

**Comment by JaroPowerH** [comment]
I'd like to work on this issue.
