### ISSUE TITLE
Add a support for `pe` module

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#230]
**Feature Category**

- [ ] Correctness
- [ ] User Interface / User Experience
- [ ] Performance
- [x] Other (please explain)

**Describe the problem**

Reported by a user: It's some organisations it's very common to use a `pe` module in Yara rules. Having a (limited) support for it would be great. 

**Describe the solution you'd like**

This rule should be optimised by the backend:
```
import "pe"

rule single_section
{
    condition:
        pe.number_of_sections == 1
}
```

**Describe alternatives you've considered**

Teach users not to use `pe` or other auxiliary modules in their yara rules. It worked for all places I've worked at, but this makes life of researchers a bit more difficult.

**Comment by msm-cert** [comment]
WONTFIX :(

I think it's time to start limitting the scope of this project. It will be implemented in one of two cases:

* We (CERT.PL) need it for our use-cases
* Someone makes a good PR that handles this in some cases

It's not a goal for this project to speed up every query, but It's probably possible to make some dumb heuristics, for example find a byte pattern that must occur in a PE with one section).
