### ISSUE TITLE
Fix regex parsing (in avast/yaramod)

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#231]
Discovered during testing a PR.

There is a bug in upstream regex parsing. Already reported here: https://github.com/avast/yaramod/issues/186. We should help yaramod fix this issue (or wait for when they have time).

**Comment by nazywam** [comment]
Should we close this @msm-code?

**Comment by msm-code** [comment]
I think we should wait for yaramod release and bump the dependency before closing this out.
