### ISSUE TITLE
Document the existence of API and its usage

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#29]
**Description**
While it is claimed by @msm-code that mquery has an API, I couldn't find any mention on this in the README nor in the repo. The API should be documented and usage examples should be provided.

**Comment by msm-code** [comment]
We probably should also improve and update ursadb API documentation (though it's usually used together with mquery)

**Comment by msm-code** [comment]
https://cert-polska.github.io/ursadb/docs/
https://cert-polska.github.io/mquery/docs/
https://cert-polska.github.io/mquery/docs/api.html
