### ISSUE TITLE
Rethink the "compact" and "index" buttons in the admin panel

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#305]
**Feature Category**

- [ ] Correctness
- [x] User Interface / User Experience
- [ ] Performance
- [ ] Other (please explain)

**Describe the problem**

The buttons are almost useless, and almost never what the user wants.

Even for very simple deployments, we should either:

- force users to use better (but more difficult) tools
- create a proper indexing UI

**Describe the solution you'd like**

Let's start with removing features, proper UI will come later :upside_down_face: (or never - probably not without a proper DB).

**Describe alternatives you've considered**

The buttons don't hurt too much, because everyone (I think) learns not to touch them. And maybe some people even find them useful sometimes. Despite that, I think that the UI in the current form should be improved or removed.

**Comment by ITAYC0HEN** [comment]
> buttons don't hurt too much, because everyone (I think) learns not to touch them 

sometimes it's learning the hard way.

Let's remove them :)
