### ISSUE TITLE
Show visible indication that no matches were found

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#32]
**Description**
It is not intuitive to understand that no matches were found for a given rule. The interface shows the table's header (why?) even though there are no matches, the progress bar isn't full, etc.

![image](https://user-images.githubusercontent.com/20182642/78384864-a2592a80-75e3-11ea-81e2-60e8bfd54cfc.png)

Instead, I suggest to show a full progress bar and then a message saying "No matches found for your rule" instead of the empty table

**Comment by msm-code** [comment]
(Assigned to @KrzyWie, working on giving him access to the project :thinking: )

**Comment by KrzyWie** [comment]
Yes, working on this
