### ISSUE TITLE
Rethink mquery's configuration

### ISSUE THREAD

**Issue by yankovs** [CERT-Polska/mquery#320]
**Feature Category**

- [ ] Correctness
- [ ] User Interface / User Experience
- [ ] Performance
- [X] Other (please explain)

**Describe the problem**

A detailed explanation can be found [here](https://github.com/CERT-Polska/mquery/pull/315#discussion_r1064934880), but the gist of it is that currently mquery's config is scattered and split into many pieces:

- deployment-related arguments (like ursadb backend url) are present in a `config.docker.py` file that is mapped to `config.py` at deployment
- plugin configuration is kept in redis under the key `plugin:<plugin_name>`
- core config (`auth_enabled`, etc) are also kept in redis, under the key `plugin:Mquery`

This results in a not very concise configuration where users (more so admins) of the system need to keep 3 places in mind when they want to do something related to configuration of mquery. Some other observations:
- plugin configuration has some boilerplate (see: #257)
- the pattern described in the first bullet point above, where `config.docker.py` is mapped into `config.py` is a simple solution to deal with docker in the project but might not be the most ideal or clean one

**Describe the solution you'd like**

Some sort of separation of concerns - don't get rid of redis but try to use it for caching and possibly plugin config. Currently what I have in mind is to move core config to a separate config file, but it is a breaking change and it introduces its own set of drawbacks (more in the link above)
Also think about the other points mentioned and try to evaluate if it really is the best solution.

**Comment by msm-code** [comment]
Thanks for creating this issue! I've already wrote half a blog post in the linked issue, so just few initial thoughts:

> don't get rid of redis but try to use it for caching and possibly plugin config

Just to be clear, redis is used for everything including job objets and lists of results. So it's way more than caching. I've added documentation for all data that is stored in reds a few days ago, but it's not merged yet: https://github.com/CERT-Polska/mquery/blob/5dc1070db34bbb4ee39c9e6157403564eb526c31/docs/redis.md

> Currently what I have in mind is to move core config to a separate config file
I quite like https://github.com/bwindsor/typed-config (this is what's used by mwdb-core - https://github.com/CERT-Polska/mwdb-core/blob/master/mwdb/core/config.py). If we are going to rewrite config handling, maybe it's a good idea.
