### ISSUE TITLE
Add a "Download All" button to download all matched samples

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#33]
**Description**
When executing a Yara from the interface, there is no way to download all the matched samples. Instead, the user needs to manually click each sample, or use the **undocumented** API.

I suggest adding two buttons for both the job and the Recent pages.
- A button to download all samples in a zip (protected with "infected" password)
- A dropdown button of buttons to download a text file
    - Download the names of the files 
    - Download the SHA256 of the files 
    - Download the SHA1 of the files 
    - Download the MD5 of the files 

Related: #16

**Comment by msm-code** [comment]
Still missing filenames, but I'll create a separate issue out of it.
