### ISSUE TITLE
Clean up iterators from disk

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#356]
**Feature Category**

- [ ] Correctness
- [ ] User Interface / User Experience
- [ ] Performance
- [x] Other (please explain)

**Describe the problem**

This is just a nitpick (after iterator GC was added to ursadb), but mquery could at least try to avoid leaving too many iterators on disk. 

**Describe the solution you'd like**

Especially "problematic" are:
 - empty iterators (if query returns 0 files, iterator is still created but never read from so never deleted)
 - cancelled queries (iterators won't be clened up)

**Describe alternatives you've considered**

Just do nothing, they will be deleted after 1 day (by default).

**Comment by msm-cert** [comment]
Unnecessary after #381 will be merged
