### ISSUE TITLE
Mquery is counting results when displaying previous jobs

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#37]
**Description**
When entering previous jobs, mquery is counting the number of matches instead of showing the number immediately.

![mquery keep counting](https://user-images.githubusercontent.com/20182642/78422224-73d06380-7666-11ea-9685-bede94991e4b.gif)

**Expected behavior**
I expect the total number of results to be shown imeediately. Even if the table is needed to be fetched (lazy loading / pagination will be better btw)

**Comment by msm-code** [comment]
Fixed with #96
