### ISSUE TITLE
[proposed enhancement] mapping index path to dataset

### ISSUE THREAD

**Issue by raw-data** [CERT-Polska/mquery#4]
From the `mquery admin` page, show `index paths` and associated `datasets`
Example:

- /mnt/sample/exe32/ dd1d25a4 gram3

- /mnt/sample/exe64/ bca025af gram3, text4

**Comment by icedevml** [comment]
Hello,

thanks for your report. Your proposition seems to be fine in terms of tracking which paths correspond to which datasets. This may be easily extended into dataset-specific queries you have proposed.

I'm going to implement that soon.

**Comment by icedevml** [comment]
Please check #5 for additional information.
