### ISSUE TITLE
Research the usefulness of accelerating xor modifier

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#51]
Accelerate rules like:

```
rule XorExample1
{
    strings:
        $xor_string = "This program cannot" xor

    condition:
       $xor_string
}
```

My gut feeling is that this may result in way too many false positives, but I may be wrong.

We should probably transform strings like this to an OR of 256 xored strings in the backend. I don't feel like first-class support in ursadb is necessary (unless someone finds a way to optimise this that needs it).

**Comment by nazywam** [comment]
So we're thinking about supporting it at yara->ursa parser level? 
The parsed queries will get a bit messy but it shouldn't be too hard.

**Comment by msm-code** [comment]
Yeah, adding it shouldn't be too hard, but we should test if it gives results fast/stable enough (the queries will get pretty big as you noted)

**Comment by ITAYC0HEN** [comment]
For reference, the XOR feature: https://yara.readthedocs.io/en/stable/writingrules.html#xor-strings
