### ISSUE TITLE
Show query duration

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#64]
**Description**
I think that it will be nice to show query duration both on the Query page as well as on the "/recent" page. It will be helpful for the user, as with the time they'll get to know the best-practices by measuring querying durations.

**Action items**
- [x] show query duration for running queries on the Query page
- [ ] show query duration for running queries on the Recent page
- [ ] show query duration for finished queries  on the Recent page
- [x] show ETA for running query

**Comment by msm-code** [comment]
:+1: . Some more ideas:

- show query duration for finished queries
- show current query duration for running queries (maybe with ETA?).
