### ISSUE TITLE
Rethink plugin system and support

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#67]
Currently we have a small set of hardcoded metadata plugins, that we recently merged with the main repo.

This system is not extensible and hard to configure, even in our environment. Think how can we improve this and open it a bit.

**Comment by msm-code** [comment]
Fixed with #110 and #131

**Comment by psrok1** [comment]
Sorry for reopening, but there are still few issues that need to be addressed: #144, #145, #146.
