### ISSUE TITLE
Yara rule test corpus

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#90]
To fight with regressions in the Yara support, we should create a find a corpus of yara rules, run them on some predefined set of files, and verify that everything is parsed and executed correctly and gives a correct results.

**Comment by ITAYC0HEN** [comment]
Florian Roth's set of yara files: https://github.com/Neo23x0/signature-base/tree/master/yara
The Yara-Rules repository: https://github.com/Yara-Rules/rules

**Comment by dskwhitehat** [comment]
Assign me please...
