### ISSUE TITLE
Implement UrsaExpression.literal

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/mquery#99]
**Feature Category**

- [ ] Correctness
- [ ] User Interface / User Experience
- [ ] Performance
- [x] Other (refactoring)

**Describe the problem**

Right now every time we want to match a literal in lib/yaraparse.py we need to write:

```python
UrsaExpression(f"{{{some_string.hex()}}}")
``` 

This is pretty repetitive and ugly

**Describe the solution you'd like**

Implement `UrsaExpression.literal` and change all occurences of this pattern to:

```python
UrsaExpression.literal(some_string)
``` 

**Describe alternatives you've considered**

Dealing with ugly code forever

**Comment by dskwhitehat** [comment]
Add me please...
